#服务器端口
server.port: 8080


# 定义数据源
spring.datasource:
    url: jdbc:mysql://192.168.2.5:3306/flowable-huangxj?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456